package com.psyche.memo.workspace

import java.io.File
import java.nio.file.Files

/**
 * 给刚装好的 rootfs 打上与 Android 宿主匹配的补丁 —— 上游 `workspace` 模块
 * `RootfsPatcher.kt:6-190` 1:1 移植。
 *
 * 依次保证：`/etc/resolv.conf` 有可用的公共 DNS、`/etc/hosts` 有 localhost 两条、
 * `/etc/hostname` 非空、`/etc/default/locale` 有 `LANG=`、`/etc/group` 补齐宿主的
 * 附加组 id（PRoot 下 Android 的 gid 在 rootfs 里没有名字，不补会让 `id`/`ls -l` 报错）、
 * 以及 `/tmp`、`/var/tmp`、`/root` 存在且可写。
 *
 * 唯一的品牌化差异：resolv.conf 首行注释写成 `# Generated by Memo workspace.`。
 */
class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return

        ensureRootfsDns(etcDir, options.nameservers)
        ensureHosts(etcDir, options.hostname)
        ensureHostname(etcDir, options.hostname)
        ensureLocale(etcDir, options.locale)
        ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureTempDirs(linuxDir)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        val existingLines = if (resolvConf.isFile) resolvConf.readLines() else emptyList()
        val existingServers = existingLines
            .filter { it.trimStart().startsWith("nameserver ") }
            .map { it.trim().removePrefix("nameserver").trim() }
            .filter { it.isNotBlank() }
        // 这个文件是不是我们生成的（首行标记）。
        val ours = existingLines.firstOrNull()?.trim() == GENERATED_DNS_MARKER
        val desired = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        val shouldWrite = when {
            Files.isSymbolicLink(resolvConf.toPath()) -> true
            !resolvConf.exists() -> true
            !resolvConf.isFile -> true
            // **我们生成的**：目标列表变了就重写。少了这一条，改了兜底 DNS 之后
            // 已装好的 rootfs 永远刷不到新值（用户 2026-09-14 就是这样踩到
            // 「1.1.1.1/8.8.8.8 不通 → apt 解析卡死 → 镜像源用不了」）。
            ours -> existingServers != desired
            // 别人（用户自己或某个包）写的：只要还有可用的非本地 nameserver 就不动。
            else -> existingServers.none { it !in LOCAL_RESOLVERS }
        }
        if (!shouldWrite) return

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        resolvConf.writeText(
            buildString {
                appendLine(GENERATED_DNS_MARKER)
                desired.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"

        /** `resolv.conf` 首行标记：用来认出「这个文件是我们生成的」。 */
        private const val GENERATED_DNS_MARKER = "# Generated by Memo workspace."

        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )

        /**
         * 兜底 DNS（调用方没给宿主 DNS 时用）。**顺序按中国大陆可达性排**：真机实测
         * 2026-09-14 —— 阿里 223.5.5.5 0.11s ✓、腾讯 119.29.29.29 0.13s ✓、
         * `8.8.8.8` **完全不通**（5s 超时）、`1.1.1.1` 时通时不通且经常要先白等一轮。
         *
         * 原顺序是 `1.1.1.1, 8.8.8.8, 223.5.5.5`，glibc 会按顺序试且各自等超时 ——
         * apt 一次 update 几十个解析叠起来就是「镜像源用不了」。所以把可达的两个放前面，
         * Cloudflare 留最后给海外用户兜底。
         */
        private val DEFAULT_DNS_SERVERS = listOf(
            "223.5.5.5",
            "119.29.29.29",
            "1.1.1.1",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
)
