-- memo.db schema v3 (drift user_version=3)
-- Generated by tools/drift_schema_to_sql.py from
-- ../drift_schemas/app_database/drift_schema_v3.json
-- 29 CREATE TABLE + 17 CREATE INDEX (1 unique); statements appended with ";".

CREATE TABLE IF NOT EXISTS "conversation_rows" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "is_pinned" INTEGER NOT NULL DEFAULT 0 CHECK ("is_pinned" IN (0, 1)), "assistant_id" TEXT NULL, "truncate_index" INTEGER NOT NULL DEFAULT -1 CHECK("truncate_index" >= -1), "version_selections_json" TEXT NOT NULL DEFAULT '{}', "summary" TEXT NULL, "last_summarized_message_count" INTEGER NOT NULL DEFAULT 0 CHECK("last_summarized_message_count" >= 0), "chat_suggestions_json" TEXT NOT NULL DEFAULT '[]', "injected_memory_hash" TEXT NULL, "last_memory_extracted_order" INTEGER NOT NULL DEFAULT -1 CHECK("last_memory_extracted_order" >= -1), "chat_model_provider" TEXT NULL, "chat_model_id" TEXT NULL, "extras_json" TEXT NOT NULL DEFAULT '{}', PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "message_rows" ("id" TEXT NOT NULL, "conversation_id" TEXT NOT NULL REFERENCES conversation_rows (id) ON DELETE CASCADE, "role" TEXT NOT NULL CHECK("role" IS NOT ''), "timestamp" INTEGER NOT NULL, "model_id" TEXT NULL, "provider_id" TEXT NULL, "total_tokens" INTEGER NULL CHECK("total_tokens" >= 0), "is_streaming" INTEGER NOT NULL DEFAULT 0 CHECK ("is_streaming" IN (0, 1)), "reasoning_start_at" INTEGER NULL, "reasoning_finished_at" INTEGER NULL, "translation" TEXT NULL, "reasoning_segments_json" TEXT NULL, "group_id" TEXT NULL, "version" INTEGER NOT NULL DEFAULT 0 CHECK("version" >= 0), "prompt_tokens" INTEGER NULL CHECK("prompt_tokens" >= 0), "completion_tokens" INTEGER NULL CHECK("completion_tokens" >= 0), "cached_tokens" INTEGER NULL CHECK("cached_tokens" >= 0), "duration_ms" INTEGER NULL CHECK("duration_ms" >= 0), "message_order" INTEGER NOT NULL CHECK("message_order" >= 0), "updated_at" INTEGER NULL, "sender_id" TEXT NULL, "extras_json" TEXT NOT NULL DEFAULT '{}', PRIMARY KEY ("id"), UNIQUE ("conversation_id", "message_order"), UNIQUE ("conversation_id", "group_id", "version"));

CREATE TABLE IF NOT EXISTS "conversation_mcp_server_rows" ("conversation_id" TEXT NOT NULL REFERENCES conversation_rows (id) ON DELETE CASCADE, "server_id" TEXT NOT NULL, "ordinal" INTEGER NOT NULL CHECK("ordinal" >= 0), PRIMARY KEY ("conversation_id", "server_id"), UNIQUE ("conversation_id", "ordinal"));

CREATE TABLE IF NOT EXISTS "chat_storage_meta_rows" ("key" TEXT NOT NULL, "value" TEXT NOT NULL, PRIMARY KEY ("key"));

CREATE TABLE IF NOT EXISTS "message_part_rows" ("part_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "conversation_id" TEXT NOT NULL, "revision_id" TEXT NOT NULL, "ordinal" INTEGER NOT NULL CHECK("ordinal" >= 0), "kind" TEXT NOT NULL CHECK("kind" IS NOT ''), "payload" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, UNIQUE ("revision_id", "ordinal"), FOREIGN KEY (revision_id) REFERENCES message_rows (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, CHECK (updated_at >= created_at));

CREATE TABLE IF NOT EXISTS "provider_artifact_rows" ("conversation_id" TEXT NOT NULL, "revision_id" TEXT NOT NULL, "kind" TEXT NOT NULL CHECK("kind" IS NOT ''), "payload" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("revision_id", "kind"), FOREIGN KEY (revision_id) REFERENCES message_rows (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, CHECK (updated_at >= created_at));

CREATE TABLE IF NOT EXISTS "asset_rows" ("id" TEXT NOT NULL, "content_hash" TEXT NOT NULL UNIQUE, "path" TEXT NOT NULL, "byte_size" INTEGER NOT NULL CHECK("byte_size" >= 0), "width" INTEGER NULL CHECK("width" > 0), "height" INTEGER NULL CHECK("height" > 0), "thumbnail_path" TEXT NULL, "created_at" INTEGER NOT NULL, "last_referenced_at" INTEGER NOT NULL, "extras_json" TEXT NOT NULL DEFAULT '{}', PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "message_asset_rows" ("conversation_id" TEXT NOT NULL, "revision_id" TEXT NOT NULL REFERENCES message_rows (id) ON DELETE CASCADE, "asset_id" TEXT NOT NULL REFERENCES asset_rows (id) ON DELETE CASCADE, "kind" TEXT NOT NULL CHECK("kind" IS NOT ''), PRIMARY KEY ("revision_id", "asset_id", "kind"));

CREATE TABLE IF NOT EXISTS "asset_gc_rows" ("asset_id" TEXT NOT NULL REFERENCES asset_rows (id) ON DELETE CASCADE, "not_before" INTEGER NOT NULL, "attempts" INTEGER NOT NULL DEFAULT 0 CHECK("attempts" >= 0), "generation" INTEGER NOT NULL DEFAULT 0 CHECK("generation" >= 0), PRIMARY KEY ("asset_id"));

CREATE TABLE IF NOT EXISTS "gc_audit_rows" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "kind" TEXT NOT NULL, "entity_id" TEXT NOT NULL, "completed_at" INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS "asset_reference_dirty_rows" ("revision_id" TEXT NOT NULL REFERENCES message_rows (id) ON DELETE CASCADE, PRIMARY KEY ("revision_id"));

CREATE TABLE IF NOT EXISTS "generation_run_rows" ("id" TEXT NOT NULL, "conversation_id" TEXT NOT NULL REFERENCES conversation_rows (id) ON DELETE CASCADE, "target_revision_id" TEXT NOT NULL, "state" TEXT NOT NULL CHECK("state" IN ('preparing', 'requesting', 'streaming', 'waiting_tool', 'completed', 'failed', 'cancelled', 'interrupted')), "state_revision" INTEGER NOT NULL DEFAULT 0 CHECK("state_revision" >= 0), "checkpoint_seq" INTEGER NOT NULL DEFAULT 0 CHECK("checkpoint_seq" >= 0), "error_code" TEXT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "terminal_at" INTEGER NULL, PRIMARY KEY ("id"), FOREIGN KEY (target_revision_id) REFERENCES message_rows (id) DEFERRABLE INITIALLY DEFERRED, CHECK (updated_at >= created_at), CHECK (terminal_at IS NULL OR terminal_at >= created_at), CHECK ((state IN ('preparing', 'requesting', 'streaming', 'waiting_tool') AND terminal_at IS NULL) OR (state IN ('completed', 'failed', 'cancelled', 'interrupted') AND terminal_at IS NOT NULL)), CHECK (error_code IS NULL OR (length(error_code) BETWEEN 1 AND 128 AND state IN ('failed', 'cancelled', 'interrupted'))));

CREATE TABLE IF NOT EXISTS "assistant_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "provider_rows" ("provider_key" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("provider_key"));

CREATE TABLE IF NOT EXISTS "provider_group_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "mcp_server_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "world_book_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "assistant_memory_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "assistant_id" TEXT NOT NULL, "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "quick_phrase_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "search_service_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "tts_service_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "instruction_injection_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "assistant_tag_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "preference_rows" ("key" TEXT NOT NULL, "value" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("key"));

CREATE TABLE IF NOT EXISTS "memory_entry_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "scope" TEXT NOT NULL CHECK("scope" IN ('global', 'assistant')), "assistant_id" TEXT NULL, "type" TEXT NOT NULL CHECK("type" IN ('identity', 'workflow', 'voice', 'instruction')), "status" TEXT NOT NULL CHECK("status" IN ('active', 'archived')), "content" TEXT NOT NULL, "content_normalized" TEXT NOT NULL, "entry_created_at" INTEGER NOT NULL, "entry_updated_at" INTEGER NOT NULL, "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"), CHECK ((scope = 'global' AND assistant_id IS NULL) OR (scope = 'assistant' AND assistant_id IS NOT NULL)), CHECK (entry_updated_at >= entry_created_at));

CREATE TABLE IF NOT EXISTS "user_profile_field_rows" ("id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "message_prompt_rows" ("revision_id" TEXT NOT NULL, "conversation_id" TEXT NOT NULL, "payload" TEXT NOT NULL, "carries_memory_snapshot" INTEGER NOT NULL DEFAULT 0 CHECK ("carries_memory_snapshot" IN (0, 1)), "created_at" INTEGER NOT NULL, PRIMARY KEY ("revision_id"), FOREIGN KEY (revision_id) REFERENCES message_rows (id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS "tombstone_rows" ("scope" TEXT NOT NULL CHECK("scope" IS NOT ''), "entity_id" TEXT NOT NULL CHECK("entity_id" IS NOT ''), "deleted_at" INTEGER NOT NULL, "payload" TEXT NOT NULL DEFAULT '{}', PRIMARY KEY ("scope", "entity_id"));

CREATE TABLE IF NOT EXISTS "extension_entity_rows" ("kind" TEXT NOT NULL CHECK("kind" IS NOT ''), "id" TEXT NOT NULL, "sort_order" INTEGER NOT NULL CHECK("sort_order" >= 0), "owner_id" TEXT NULL, "payload" TEXT NOT NULL, "updated_at" INTEGER NOT NULL, PRIMARY KEY ("kind", "id"));

CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC);

CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id);

CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id);

CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id);

CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id);

CREATE INDEX idx_message_rows_streaming ON message_rows (id) WHERE is_streaming = 1;

CREATE INDEX idx_message_parts_revision_ordinal ON message_part_rows (conversation_id, revision_id, ordinal);

CREATE INDEX idx_provider_artifacts_revision_kind ON provider_artifact_rows (conversation_id, revision_id, kind);

CREATE INDEX idx_message_assets_asset ON message_asset_rows (asset_id, revision_id);

CREATE UNIQUE INDEX idx_generation_runs_active_target ON generation_run_rows (conversation_id, target_revision_id) WHERE state IN ('preparing', 'requesting', 'streaming', 'waiting_tool');

CREATE INDEX idx_generation_runs_state_updated ON generation_run_rows (state, updated_at, id);

CREATE INDEX idx_assistant_memories_assistant ON assistant_memory_rows (assistant_id, id);

CREATE INDEX idx_memory_entries_visible ON memory_entry_rows (status, type, scope, assistant_id);

CREATE INDEX idx_memory_entries_recent ON memory_entry_rows (status, type, entry_updated_at, id);

CREATE INDEX idx_memory_entries_dedupe ON memory_entry_rows (scope, assistant_id, type, content_normalized);

CREATE INDEX idx_message_prompts_conversation_snapshot ON message_prompt_rows (conversation_id, carries_memory_snapshot);

CREATE INDEX idx_extension_entities_kind_order ON extension_entity_rows (kind, sort_order);
