# -*- coding: utf-8 -*-
"""Extract drift schema v3 DDL (fixed_sql) into a single executable .sql asset.

Usage:
    python tools/drift_schema_to_sql.py
        [--json drift_schemas/app_database/drift_schema_v3.json]
        [--out ../core/data/src/main/assets/memo_schema_v3.sql]
        [--verify]   # execute the emitted SQL in an in-memory sqlite3 and print counts

Facts source of truth: drift_schemas/app_database/drift_schema_v3.json `fixed_sql`,
an array of {"name": ..., "sql": [{"dialect": "sqlite", "sql": "..."}]}.
Expected composition: 29 CREATE TABLE + 16 CREATE INDEX + 1 CREATE UNIQUE INDEX.
No statement in the source contains ';' inside the body; we append one per statement.
"""
from __future__ import print_function

import argparse
import json
import os

MODULE_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SCHEMA_RELPATH = os.path.join('drift_schemas', 'app_database', 'drift_schema_v3.json')


def default_schema_json():
    """schema JSON 的位置：发布仓里 `drift_schemas/` 就在仓根；开发仓里 Memo 只是
    外层仓的一个子目录，输入在外层。两种布局都找得到，找不到就把仓根那个路径报出去。
    """
    for base in (MODULE_ROOT, os.path.normpath(os.path.join(MODULE_ROOT, '..'))):
        candidate = os.path.join(base, SCHEMA_RELPATH)
        if os.path.isfile(candidate):
            return candidate
    return os.path.join(MODULE_ROOT, SCHEMA_RELPATH)
import re
import sqlite3
import sys

EXPECTED_TABLES = 29
EXPECTED_INDEXES = 17  # includes the single CREATE UNIQUE INDEX


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument('--json', default=default_schema_json())
    ap.add_argument('--out', default=os.path.normpath(os.path.join(
        here, '..', 'core', 'data', 'src', 'main', 'assets', 'memo_schema_v3.sql')))
    ap.add_argument('--verify', action='store_true')
    args = ap.parse_args()

    with open(args.json, 'r', encoding='utf-8') as f:
        data = json.load(f)

    fixed = data.get('fixed_sql')
    if not isinstance(fixed, list) or not fixed:
        print('error: no fixed_sql array found in %s' % args.json, file=sys.stderr)
        return 1

    statements = []
    for entry in fixed:
        name = entry.get('name')
        sqls = entry.get('sql', [])
        if not isinstance(sqls, list):
            print('error: entry %s has non-list sql' % name, file=sys.stderr)
            return 1
        sqlite_sql = []
        for s in sqls:
            if isinstance(s, dict) and s.get('dialect') == 'sqlite':
                sqlite_sql.append(s.get('sql'))
        if len(sqlite_sql) != 1:
            print('error: entry %s has %d sqlite statements, expected 1'
                  % (name, len(sqlite_sql)), file=sys.stderr)
            return 1
        statements.append(sqlite_sql[0])

    tables = [s for s in statements if s.lstrip().upper().startswith('CREATE TABLE')]
    indexes = [s for s in statements if s.lstrip().upper().startswith('CREATE INDEX')]
    uniques = [s for s in statements if s.lstrip().upper().startswith('CREATE UNIQUE INDEX')]
    other = [s for s in statements if not (s.lstrip().upper().startswith('CREATE TABLE')
                                           or s.lstrip().upper().startswith('CREATE INDEX')
                                           or s.lstrip().upper().startswith('CREATE UNIQUE INDEX'))]

    if other:
        print('error: unexpected statement kinds:', other, file=sys.stderr)
        return 1
    if len(tables) != EXPECTED_TABLES:
        print('error: expected %d CREATE TABLE, got %d' % (EXPECTED_TABLES, len(tables)),
              file=sys.stderr)
        return 1
    if len(indexes) + len(uniques) != EXPECTED_INDEXES:
        print('error: expected %d CREATE INDEX statements, got %d'
              % (EXPECTED_INDEXES, len(indexes) + len(uniques)), file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    # 头部注释写**逻辑输入路径**（不写本机绝对路径，也不写相对 `tools/` 的 ../ 形式）：
    # 这份 .sql 会随源码发布，写死 D:\... 会泄漏本机目录；而开发仓（输入在外层）与
    # 发布仓（输入在仓根）两种布局下的相对路径也不一样 —— 任一写法都会让另一棵树
    # 重新生成时报假 diff，门禁的 `git diff --exit-code` 就红。
    shown = SCHEMA_RELPATH.replace(os.sep, '/')
    header = [
        '-- memo.db schema v3 (drift user_version=3)',
        '-- Generated by tools/drift_schema_to_sql.py from',
        '-- %s' % shown,
        '-- %d CREATE TABLE + %d CREATE INDEX (1 unique); statements appended with ";".'
        % (len(tables), len(indexes) + len(uniques)),
        '',
    ]
    body = []
    for s in statements:
        s = s.rstrip()
        while s.endswith(';'):
            s = s[:-1].rstrip()
        body.append(s + ';')
    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(header) + '\n' + '\n\n'.join(body) + '\n')

    print('wrote %s (%d statements)' % (args.out, len(statements)))

    if args.verify:
        conn = sqlite3.connect(':memory:')
        for s in statements:
            conn.execute(s)
        cur = conn.execute(
            "SELECT type, COUNT(*) FROM sqlite_master WHERE type IN ('table','index')"
            " AND name NOT LIKE 'sqlite_%' GROUP BY type ORDER BY type")
        counts = dict(cur.fetchall())
        conn.close()
        print('verify: sqlite_master counts -> tables=%s indexes=%s'
              % (counts.get('table'), counts.get('index')))
        if counts.get('table') != EXPECTED_TABLES or counts.get('index') != EXPECTED_INDEXES:
            print('error: verification mismatch', file=sys.stderr)
            return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
