# -*- coding: utf-8 -*-
"""Generate MemoPalettes.kt from lib/theme/palettes.dart (read-only source).

Parses each `static const ThemePalette <name> = ThemePalette(...)` block and
transcribes its light/dark ColorScheme constructor arguments verbatim into
Compose material3 ColorScheme builder calls.

Flutter -> Compose role mapping:
  - argument names are identical for the roles memo declares
  - onInverseSurface -> inverseOnSurface
  - shadow: no Compose ColorScheme member -> dropped
  - brightness -> light/darkColorScheme() selection
Flutter's ColorScheme leaves container/background roles unspecified; memo
surfaces are near-neutral and the app relies on them for cards/chips, so every
Compose surfaceContainer*/surfaceDim/Bright/surfaceVariant/background role is
flattened to the palette's surface value (and onBackground to onSurface).

Usage: python tools/palettes_gen.py
"""
from __future__ import print_function

import os
from upstream_root import upstream_root
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PALETTES_DART = os.path.join(upstream_root(HERE), 'lib', 'theme', 'palettes.dart')
OUT_KT = os.path.normpath(os.path.join(HERE, '..', 'core', 'ui', 'src', 'main', 'java',
                                        'com', 'psyche', 'memo', 'ui', 'theme', 'Palettes.kt'))

PALETTE_RE = re.compile(r'static const ThemePalette\s+(\w+)\s*=\s*ThemePalette\s*\(')
ID_CONST_RE = re.compile(r"static const String (\w+Id) = '([^']*)'")
ARG_RE = re.compile(r'(\w+):\s*Color\((0x[0-9A-Fa-f]{8})\)')
FIELD_RE = re.compile(r"(\w+):\s*'([^']*)'")

# Flutter arg name -> compose builder arg name (None = drop)
ROLE_MAP = {
    'primary': 'primary', 'onPrimary': 'onPrimary',
    'primaryContainer': 'primaryContainer', 'onPrimaryContainer': 'onPrimaryContainer',
    'secondary': 'secondary', 'onSecondary': 'onSecondary',
    'secondaryContainer': 'secondaryContainer', 'onSecondaryContainer': 'onSecondaryContainer',
    'tertiary': 'tertiary', 'onTertiary': 'onTertiary',
    'tertiaryContainer': 'tertiaryContainer', 'onTertiaryContainer': 'onTertiaryContainer',
    'error': 'error', 'onError': 'onError',
    'errorContainer': 'errorContainer', 'onErrorContainer': 'onErrorContainer',
    'surface': 'surface', 'onSurface': 'onSurface',
    'surfaceVariant': 'surfaceVariant', 'onSurfaceVariant': 'onSurfaceVariant',
    'outline': 'outline', 'outlineVariant': 'outlineVariant',
    'scrim': 'scrim', 'inverseSurface': 'inverseSurface',
    'inversePrimary': 'inversePrimary', 'surfaceTint': 'surfaceTint',
    'onInverseSurface': 'inverseOnSurface',
    'shadow': None,
}

# Compose roles memo never declares, flattened to the palette surface value.
CONTAINER_ROLES = ['surfaceVariant', 'surfaceContainerLowest', 'surfaceContainerLow',
                   'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest',
                   'surfaceDim', 'surfaceBright', 'background']


def balanced(text, open_idx):
    """End index (exclusive) of the paren group starting at text[open_idx] == '('."""
    depth = 0
    for i in range(open_idx, len(text)):
        if text[i] == '(':
            depth += 1
        elif text[i] == ')':
            depth -= 1
            if depth == 0:
                return i
    raise ValueError('unbalanced parens from %d' % open_idx)


def scheme_args(body, field):
    """Ordered list of (compose_role, int_argb) inside `field: ColorScheme(...)`."""
    start = body.index('%s: ColorScheme(' % field)
    block = body[start:balanced(body, body.index('(', start)) + 1]
    args = []
    for k, v in ARG_RE.findall(block):
        cn = ROLE_MAP.get(k)
        if cn is not None and k != 'brightness':
            args.append((cn, int(v, 16)))
    return args


def color_kt(role, argb):
    return '        %s = Color(0x%08X),' % (role, argb)


def main():
    with open(PALETTES_DART, 'r', encoding='utf-8') as f:
        dart = f.read()

    chunks = []
    id_by_const = dict(ID_CONST_RE.findall(dart))
    for m in PALETTE_RE.finditer(dart):
        name = m.group(1)
        open_idx = dart.index('(', m.start())
        body = dart[m.end():balanced(dart, open_idx)]
        fields = dict(FIELD_RE.findall(body))
        id_m = re.search(r'\bid:\s*(?:(\w+Id)|"([^"]*)"|\'([^\']*)\')', body)
        pid = None
        if id_m:
            pid = id_by_const.get(id_m.group(1)) if id_m.group(1) else (id_m.group(2) or id_m.group(3))
        var_name = name[:-len('Palette')] if name.endswith('Palette') else name
        chunks.append((var_name, pid, fields.get('zhName'), fields.get('enName')))
    if len(chunks) != 9:
        print('error: expected 9 palettes, found %d' % len(chunks), file=sys.stderr)
        return 1

    out = []
    out.append('// GENERATED by tools/palettes_gen.py from lib/theme/palettes.dart - DO NOT EDIT')
    out.append('package com.psyche.memo.ui.theme')
    out.append('')
    out.append('import androidx.compose.material3.ColorScheme')
    out.append('import androidx.compose.material3.darkColorScheme')
    out.append('import androidx.compose.material3.lightColorScheme')
    out.append('import androidx.compose.ui.graphics.Color')
    out.append('')
    out.append('data class Palette(')
    out.append('    val id: String,')
    out.append('    val zhName: String,')
    out.append('    val enName: String,')
    out.append('    val light: ColorScheme,')
    out.append('    val dark: ColorScheme,')
    out.append(')')
    out.append('')

    def flatten(scheme_pairs):
        """Append compose-only container/background roles after the written roles."""
        lines = []
        for role, argb in scheme_pairs:
            lines.append(color_kt(role, argb))
        written = set(r for r, _ in scheme_pairs)
        surface = next(argb for r, argb in scheme_pairs if r == 'surface')
        on_surface = next(argb for r, argb in scheme_pairs if r == 'onSurface')
        for role in CONTAINER_ROLES:
            if role not in written:
                lines.append(color_kt(role, surface))
        if 'onBackground' not in written:
            lines.append(color_kt('onBackground', on_surface))
        return lines

    for name, pid, zh, en in chunks:
        if pid is None or zh is None or en is None:
            print('error: missing id/zh/en for %s' % name, file=sys.stderr)
            return 1
        start = dart.index('static const ThemePalette %s' % name)
        open_idx = dart.index('(', start)
        body = dart[PALETTE_RE.search(dart, start).end():balanced(dart, open_idx)]
        out.append('val %sPalette = Palette(' % name)
        out.append('    id = "%s",' % pid)
        out.append('    zhName = "%s",' % zh)
        out.append('    enName = "%s",' % en)
        for field, ctor in (('light', 'lightColorScheme'), ('dark', 'darkColorScheme')):
            out.append('    %s = %s(' % (field, ctor))
            out.extend(flatten(scheme_args(body, field)))
            out.append('    ),')
        out.append(')')
        out.append('')

    out.append('val allPalettes: List<Palette> = listOf(')
    for name, _, _, _ in chunks:
        out.append('    %sPalette,' % name)
    out.append(')')
    out.append('')
    out.append('fun paletteById(id: String): Palette =')
    out.append('    allPalettes.firstOrNull { it.id == id } ?: %sPalette' % chunks[0][0])
    out.append('')

    os.makedirs(os.path.dirname(OUT_KT), exist_ok=True)
    with open(OUT_KT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('wrote %s (%d palettes)' % (OUT_KT, len(chunks)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
