# -*- coding: utf-8 -*-
"""Generate SettingsKeyRegistry.kt from the Dart business settings key registry.

Usage:
    python tools/settings_keys_gen.py
        [--router ../lib/core/database/business_settings_router.dart]
        [--entities ../lib/core/database/business_data.dart]
        [--out ../core/data/src/main/java/com/psyche/memo/data/settings/SettingsKeyRegistry.kt]

The Dart side is the single source of truth for key membership:
- business_settings_router.dart declares localOnlyKeys / discardedKeys / preferenceKeys
  sets plus a classify() that also special-cases 'restore_*' and 'display_*' prefixes.
- business_data.dart declares BusinessEntityKind(sourceKey: ..., ...) entries.

The generated Kotlin file contains only the sets; classify() logic mirrors the Dart
order of checks and lives in the same file. Assertion counts are derived from the
sets actually parsed, not hardcoded, but localOnlyKeys must stay 9.
"""
from __future__ import print_function

import argparse
import os
from upstream_root import upstream_root
import re
import sys

LOCAL_ONLY_EXPECTED = 9


def extract_string_set(text, name):
    m = re.search(r'static const %sKeys = <String>\{(.*?)\};' % name, text, re.S)
    if not m:
        raise RuntimeError('set %sKeys not found' % name)
    return sorted(set(re.findall(r"'([^']+)'", m.group(1))))


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    repo = upstream_root(here)
    ap.add_argument('--router', default=os.path.join(
        repo, 'lib', 'core', 'database', 'business_settings_router.dart'))
    ap.add_argument('--entities', default=os.path.join(
        repo, 'lib', 'core', 'database', 'business_data.dart'))
    ap.add_argument('--out', default=os.path.join(
        here, '..', 'core', 'data', 'src', 'main', 'java',
        'com', 'psyche', 'memo', 'data', 'settings', 'SettingsKeyRegistry.kt'))
    args = ap.parse_args()

    with open(args.router, 'r', encoding='utf-8') as f:
        router_text = f.read()
    with open(args.entities, 'r', encoding='utf-8') as f:
        entities_text = f.read()

    local_only = extract_string_set(router_text, 'localOnly')
    discarded = extract_string_set(router_text, 'discarded')
    preference = extract_string_set(router_text, 'preference')
    entity_keys = sorted(set(re.findall(r"sourceKey:\s*'([^']+)'", entities_text)))

    if len(local_only) != LOCAL_ONLY_EXPECTED:
        print('error: localOnlyKeys count %d != %d' % (len(local_only), LOCAL_ONLY_EXPECTED),
              file=sys.stderr)
        return 1
    if not discarded or not preference or not entity_keys:
        print('error: one of the parsed sets is empty', file=sys.stderr)
        return 1

    def emit_set(var_name, keys):
        out = ['    val %s: Set<String> = setOf(' % var_name]
        for i in range(0, len(keys), 3):
            chunk = ', '.join('"%s"' % k for k in keys[i:i + 3])
            out.append('        %s,' % chunk)
        out.append('    )')
        return out

    lines = []
    lines.append('package com.psyche.memo.data.settings')
    lines.append('')
    lines.append('// GENERATED by tools/settings_keys_gen.py - DO NOT HAND-EDIT.')
    lines.append('// Sources of truth:')
    lines.append('//   lib/core/database/business_settings_router.dart')
    lines.append('//   lib/core/database/business_data.dart (entity sourceKeys)')
    lines.append('object SettingsKeyRegistry {')
    for var_name, keys in (('LOCAL_ONLY_KEYS', local_only),
                           ('DISCARDED_KEYS', discarded),
                           ('PREFERENCE_KEYS', preference),
                           ('ENTITY_SOURCE_KEYS', entity_keys)):
        lines.extend(emit_set(var_name, keys))
        lines.append('')
    lines.append('    const val PROVIDER_ORDER_KEY = "providers_order_v1"')
    lines.append('')
    lines.append('    val ALL_KEYS: Set<String> =')
    lines.append('        LOCAL_ONLY_KEYS + DISCARDED_KEYS + PREFERENCE_KEYS + ENTITY_SOURCE_KEYS + setOf(PROVIDER_ORDER_KEY)')
    lines.append('}')
    lines.append('')
    lines.append('enum class KeyDisposition { ENTITY, PROVIDER_ORDER, PREFERENCE, LOCAL_ONLY, DISCARDED, UNKNOWN }')
    lines.append('')
    lines.append('// Mirrors BusinessKeyRegistry.classify() check order.')
    lines.append('fun classifyBusinessKey(key: String): KeyDisposition {')
    lines.append('    if (key in SettingsKeyRegistry.ENTITY_SOURCE_KEYS) return KeyDisposition.ENTITY')
    lines.append('    if (key == SettingsKeyRegistry.PROVIDER_ORDER_KEY) return KeyDisposition.PROVIDER_ORDER')
    lines.append('    if (key in SettingsKeyRegistry.LOCAL_ONLY_KEYS || key.startsWith("restore_")) return KeyDisposition.LOCAL_ONLY')
    lines.append('    if (key in SettingsKeyRegistry.DISCARDED_KEYS) return KeyDisposition.DISCARDED')
    lines.append('    if (key in SettingsKeyRegistry.PREFERENCE_KEYS || key.startsWith("display_")) return KeyDisposition.PREFERENCE')
    lines.append('    return KeyDisposition.UNKNOWN')
    lines.append('}')

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    print('wrote %s' % args.out)
    print('counts: localOnly=%d discarded=%d preference=%d entity=%d'
          % (len(local_only), len(discarded), len(preference), len(entity_keys)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
