package com.psyche.memo.workspace

import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import okio.Buffer
import org.junit.Assert.*
import org.junit.Assume
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.File
import java.nio.file.Files
import java.util.zip.GZIPOutputStream

/**
 * 工作区核心的行为用例 —— 上游 `workspace/src/test/.../ExampleUnitTest.kt:12-263` 移植。
 *
 * 三处适配：
 *  1. 品牌串断言：resolv.conf 首行注释由上游品牌改成 `# Generated by Memo workspace.`；
 *  2. 本地 HTTP 服务端：上游用 JDK 的 `com.sun.net.httpserver.HttpServer`，但本模块
 *     Kotlin 编译器（Android + jvmTarget 11）看不到 `com.sun.*`，改用工程内已有的
 *     okhttp `MockWebServer`（`core:llm` 的集成测试同款），断言不变；
 *  3. 依赖宿主 POSIX shell 的 4 个 case（上游用 `/bin/sh` 执行 `awk`/`cat`）在 Windows
 *     开发机上没有 `/bin/sh`，用 [Assume] 跳过 —— 断言原样保留，只在 POSIX 宿主（CI /
 *     Android）上跑；另加一条不依赖宿主的 [processOutputIsTruncatedAtLimit] 覆盖同一个
 *     128 KiB 上限。
 */
class ExampleUnitTest {
    @Test
    fun fileOperationsWorkInsideWorkspaceRoot() {
        val root = Files.createTempDirectory("workspace-test").toFile()
        val fileSystem = WorkspaceFileSystem()

        fileSystem.writeText(root, "src/main.txt", "hello\nworkspace")

        assertEquals("hello\nworkspace", fileSystem.readText(root, "src/main.txt"))
        assertEquals(listOf("src"), fileSystem.list(root).map { it.path })
        assertEquals(listOf("src/main.txt"), fileSystem.glob(root, "**/*.txt").map { it.path })
        assertEquals(
            listOf(WorkspaceSearchMatch(path = "src/main.txt", line = 2, text = "workspace")),
            fileSystem.grep(root, "workspace"),
        )
    }

    @Test
    fun pathEscapeIsRejected() {
        val root = Files.createTempDirectory("workspace-test").toFile()
        val fileSystem = WorkspaceFileSystem()

        var rejected = false
        try {
            fileSystem.writeText(root, "../escape.txt", "nope")
        } catch (_: IllegalArgumentException) {
            rejected = true
        }
        assertTrue(rejected)
    }

    @Test
    fun rootfsRequiresShellEntryPoint() {
        val baseDir = Files.createTempDirectory("workspace-manager-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        assertFalse(manager.hasRootfs(root))

        File(manager.linuxDir(root), "etc").mkdirs()
        assertFalse(manager.hasRootfs(root))

        File(manager.linuxDir(root), "bin").mkdirs()
        File(manager.linuxDir(root), "bin/sh").writeText("#!/bin/sh\n")
        assertTrue(manager.hasRootfs(root))
    }

    @Test
    fun rootfsInstallerDownloadsAndExtractsTarGz() {
        val baseDir = Files.createTempDirectory("workspace-manager-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val installer = RootfsInstaller(manager)
        val archive = tarGz(
            TarTestEntry("bin/", type = '5'),
            TarTestEntry("bin/hello", content = "echo hello\n".toByteArray(), mode = 493),
            TarTestEntry("usr/bin/hello-link", type = '2', linkName = "../../bin/hello"),
        )
        val server = MockWebServer()
        server.enqueue(
            MockResponse()
                .setResponseCode(200)
                .setBody(Buffer().write(archive))
        )
        server.start()
        try {
            val root = "test-workspace"
            installer.install(root, server.url("/rootfs.tar.gz").toString())

            val linuxDir = manager.linuxDir(root)
            assertEquals("echo hello\n", File(linuxDir, "bin/hello").readText())
            assertTrue(File(linuxDir, "bin/hello").canExecute())
            assertTrue(Files.isSymbolicLink(File(linuxDir, "usr/bin/hello-link").toPath()))
        } finally {
            server.shutdown()
        }
    }

    @Test
    fun commandRunsInsideWorkspaceFilesDirectory() {
        requireHostPosixShell()
        val baseDir = Files.createTempDirectory("workspace-command-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        val result = manager.executeCommand(root, "printf hello > command.txt && cat command.txt")

        assertEquals(0, result.exitCode)
        assertEquals("hello", result.stdout)
        assertEquals("hello", File(manager.filesDir(root), "command.txt").readText())
    }

    @Test
    fun commandReceivesStdin() {
        requireHostPosixShell()
        val baseDir = Files.createTempDirectory("workspace-stdin-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        val result = manager.executeCommand(
            root = root,
            command = "cat > stdin.txt",
            stdin = "hello\nstdin".toByteArray(),
        )

        assertEquals(0, result.exitCode)
        assertEquals("hello\nstdin", File(manager.filesDir(root), "stdin.txt").readText())
    }

    @Test
    fun commandWithoutStdinGetsImmediateEof() {
        requireHostPosixShell()
        val baseDir = Files.createTempDirectory("workspace-stdin-eof-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        // 不传 stdin 时子进程的 stdin 应立即 EOF; cat 会直接退出而不是等管道输入
        val result = manager.executeCommand(
            root = root,
            command = "cat",
            timeoutMillis = 10_000,
        )

        assertFalse(result.timedOut)
        assertEquals(0, result.exitCode)
        assertEquals("", result.stdout)
    }

    @Test
    fun prootRunnerRequiresRootfs() {
        val baseDir = Files.createTempDirectory("workspace-proot-test").toFile()
        val manager = WorkspaceManager(
            baseDir = baseDir,
            shellRunner = ProotShellRunner(File(baseDir, "native"))
        )
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        val result = manager.executeCommand(root, "cat /etc/os-release")

        assertEquals(127, result.exitCode)
        assertEquals("Rootfs is not installed", result.stderr)
    }

    @Test
    fun commandOutputIsTruncatedAtLimit() {
        requireHostPosixShell()
        val baseDir = Files.createTempDirectory("workspace-truncate-test").toFile()
        val manager = WorkspaceManager(baseDir)
        val root = "test-workspace"
        manager.ensureWorkspace(root)

        val result = manager.executeCommand(
            root,
            "awk 'BEGIN { for (i = 0; i < 300000; i++) printf \"a\" }'",
        )

        assertEquals(0, result.exitCode)
        assertTrue(result.truncated)
        assertEquals(MAX_OUTPUT_CHARS, result.stdout.length)
    }

    /**
     * 同一条上限断言的不依赖宿主的版本：用 JDK 自带的源码启动器（`java Flood.java`，
     * JEP 330）造一个输出 400000 字符的子进程，直接验证 [readResult] 的 128 KiB 截断。
     */
    @Test
    fun processOutputIsTruncatedAtLimit() {
        val dir = Files.createTempDirectory("workspace-truncate-jvm-test").toFile()
        val source = File(dir, "Flood.java")
        source.writeText(
            """
            public class Flood {
                public static void main(String[] args) {
                    char[] chunk = new char[4096];
                    java.util.Arrays.fill(chunk, 'a');
                    for (int i = 0; i < 100; i++) {
                        System.out.print(chunk);
                    }
                    System.out.flush();
                }
            }
            """.trimIndent() + "\n"
        )
        val java = File(File(System.getProperty("java.home"), "bin"), "java").absolutePath
        val process = ProcessBuilder(java, source.absolutePath)
            .directory(dir)
            .redirectErrorStream(false)
            .start()

        val result = process.readResult(60_000)

        assertEquals(0, result.exitCode)
        assertTrue(result.truncated)
        assertEquals(MAX_OUTPUT_CHARS, result.stdout.length)
    }

    @Test
    fun rootfsPatcherAppliesAndroidProotDefaults() {
        val linuxDir = Files.createTempDirectory("rootfs-patch-test").toFile()
        File(linuxDir, "etc").mkdirs()
        File(linuxDir, "etc/resolv.conf").writeText("nameserver 127.0.0.53\n")
        File(linuxDir, "etc/group").writeText("root:x:0:\n")

        RootfsPatcher().patch(
            linuxDir,
            RootfsPatchOptions(
                nameservers = listOf("9.9.9.9", "8.8.8.8"),
                hostname = "workspace-test",
                groupIds = listOf(3003, 9997),
            )
        )

        assertEquals(
            """
            # Generated by Memo workspace.
            nameserver 9.9.9.9
            nameserver 8.8.8.8
            options edns0 trust-ad

            """.trimIndent(),
            File(linuxDir, "etc/resolv.conf").readText()
        )
        assertTrue(File(linuxDir, "etc/hosts").readText().contains("127.0.0.1 localhost workspace-test"))
        assertEquals("workspace-test\n", File(linuxDir, "etc/hostname").readText())
        assertEquals("LANG=C.UTF-8\n", File(linuxDir, "etc/default/locale").readText())
        assertTrue(File(linuxDir, "etc/group").readText().contains("android_gid_3003:x:3003:"))
        assertTrue(File(linuxDir, "etc/group").readText().contains("android_gid_9997:x:9997:"))
        assertTrue(File(linuxDir, "tmp").canWrite())
        assertTrue(File(linuxDir, "var/tmp").canWrite())
        assertTrue(File(linuxDir, "root").isDirectory)
    }

    /**
     * 我们自己生成的 `resolv.conf` 必须能跟着兜底列表一起更新。
     *
     * 用户 2026-09-14「这个镜像源为什么用不了呀」的根因就在这里：兜底 DNS 原来是
     * `1.1.1.1, 8.8.8.8, 223.5.5.5`（实测 `8.8.8.8` 完全不通、`1.1.1.1` 时通时不通），
     * 而旧的守卫是「有非本地 nameserver 就不动」—— 改了兜底列表也刷不到**已经装好**的
     * rootfs，于是 apt 每次解析都先白等两轮超时。
     */
    @Test
    fun rootfsPatcherRefreshesItsOwnStaleResolvConf() {
        val linuxDir = Files.createTempDirectory("rootfs-dns-refresh").toFile()
        File(linuxDir, "etc").mkdirs()
        // 上一版生成的文件（首行是我们的标记 + 旧的兜底列表）。
        File(linuxDir, "etc/resolv.conf").writeText(
            """
            # Generated by Memo workspace.
            nameserver 1.1.1.1
            nameserver 8.8.8.8
            nameserver 223.5.5.5
            options edns0 trust-ad

            """.trimIndent(),
        )

        RootfsPatcher().patch(linuxDir)

        val text = File(linuxDir, "etc/resolv.conf").readText()
        assertEquals(
            """
            # Generated by Memo workspace.
            nameserver 223.5.5.5
            nameserver 119.29.29.29
            nameserver 1.1.1.1
            options edns0 trust-ad

            """.trimIndent(),
            text,
        )
    }

    /** 别人写的 resolv.conf（没有我们的标记）只要还有可用 nameserver 就不该被动。 */
    @Test
    fun rootfsPatcherKeepsForeignResolvConf() {
        val linuxDir = Files.createTempDirectory("rootfs-dns-foreign").toFile()
        File(linuxDir, "etc").mkdirs()
        File(linuxDir, "etc/resolv.conf").writeText("nameserver 10.0.0.1\n")

        RootfsPatcher().patch(linuxDir)

        assertEquals(
            "nameserver 10.0.0.1\n",
            File(linuxDir, "etc/resolv.conf").readText(),
        )
    }

    /**
     * [HostShellRunner] 只认 `/system/bin/sh` 或 `/bin/sh`（Android 与 Linux CI 上有，
     * Windows 开发机上没有），进程根本起不来。这里跳过而不是把断言改弱 —— 这些 case 的
     * 行为在 POSIX 宿主上仍然逐条生效。
     */
    private fun requireHostPosixShell() {
        Assume.assumeTrue(
            "宿主没有 POSIX shell（/bin/sh），跳过宿主 shell 用例",
            File("/system/bin/sh").exists() || File("/bin/sh").exists(),
        )
    }

    private fun tarGz(vararg entries: TarTestEntry): ByteArray {
        val output = ByteArrayOutputStream()
        GZIPOutputStream(output).use { gzip ->
            entries.forEach { entry ->
                gzip.write(tarHeader(entry))
                if (entry.content.isNotEmpty()) {
                    gzip.write(entry.content)
                    gzip.write(ByteArray(entry.content.size.paddingSize()))
                }
            }
            gzip.write(ByteArray(1024))
        }
        return output.toByteArray()
    }

    private fun tarHeader(entry: TarTestEntry): ByteArray {
        val header = ByteArray(512)
        header.writeString(0, 100, entry.name)
        header.writeOctal(100, 8, entry.mode.toLong())
        header.writeOctal(108, 8, 0)
        header.writeOctal(116, 8, 0)
        header.writeOctal(124, 12, entry.content.size.toLong())
        header.writeOctal(136, 12, 0)
        header.fill(' '.code.toByte(), 148, 156)
        header[156] = entry.type.code.toByte()
        header.writeString(157, 100, entry.linkName)
        header.writeString(257, 6, "ustar")
        header.writeString(263, 2, "00")
        val checksum = header.sumOf { it.toUByte().toInt() }
        header.writeOctal(148, 8, checksum.toLong())
        return header
    }

    private fun ByteArray.writeString(offset: Int, length: Int, value: String) {
        val bytes = value.toByteArray()
        bytes.copyInto(this, offset, 0, minOf(bytes.size, length))
    }

    private fun ByteArray.writeOctal(offset: Int, length: Int, value: Long) {
        val text = value.toString(8).padStart(length - 1, '0')
        writeString(offset, length, text)
        this[offset + length - 1] = 0
    }

    private fun Int.paddingSize(): Int = (512 - (this % 512)).let {
        if (it == 512) 0 else it
    }

    private data class TarTestEntry(
        val name: String,
        val content: ByteArray = byteArrayOf(),
        val mode: Int = 420,
        val type: Char = '0',
        val linkName: String = "",
    )
}
